---
- name: Converge
  hosts: all
  vars:
    django_app_path: /app/django-blog
    django_virtualenv: /venv
    django_main_commands:
      - command: migrate
      - command: loaddata
        fixtures: users posts comments
    django_user: root
    uwsgi_os_packages:
      - uwsgi
      - uwsgi-plugin-python
    uwsgi_use_systemd: true
    uwsgi_vassals:
      - name: blog
        plugin: python36u
        chdir: /app/django-blog
        home: /venv
        module: mysite.wsgi:application
        env: DJANGO_SETTINGS_MODULE=mysite.settings
        master: true
        processes: 5
        chmod-socket: 666
        socket: /run/uwsgi/uwsgi.sock
        uid: uwsgi
        gid: uwsgi
        vacuum: true
        max-requests: 1000

#  roles:
#    - role: molecule_example
    - role: cchurch.django
    - role: cchurch.uwsgi

  tasks:
    - name: "Enable uwsgi through nginx"
      template:
        src: etc/nginx/conf.d/uwsgi.conf.j2
        dest: /etc/nginx/conf.d/uwsgi.conf
        mode: 0755
        owner: root
        group: root
      notify: restart nginx

    - name: "Fix allowed host headers"
      lineinfile:
        path: /app/django-blog/mysite/settings.py
        regexp: '^ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
      notify: restart uwsgi

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: restart uwsgi
      service:
        name: uwsgi
        state: restarted
